<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>3D Anatomy Explorer | MedixAR</title>

    @vite(['resources/css/app.css'])

    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Google Model Viewer Component -->
    <script type="module" src="https://ajax.googleapis.com/ajax/libs/model-viewer/3.4.0/model-viewer.min.js"></script>

    <style>
        body { font-family: 'Outfit', sans-serif; overflow: hidden; }
        
        .glass-nav {
            background: rgba(5, 11, 9, 0.7);
            backdrop-filter: blur(24px);
            border-bottom: 1px solid rgba(255,255,255,0.05);
        }
        
        .glass-panel {
            background: rgba(10, 25, 22, 0.45);
            backdrop-filter: blur(24px);
            border: 1px solid rgba(255,255,255,0.08);
        }

        ::-webkit-scrollbar { width: 6px; }
        ::-webkit-scrollbar-track { background: transparent; }
        ::-webkit-scrollbar-thumb { background: rgba(45, 212, 191, 0.3); border-radius: 10px; }
        ::-webkit-scrollbar-thumb:hover { background: rgba(45, 212, 191, 0.6); }

        model-viewer::part(default-ar-button) {
            background-color: rgba(20, 184, 166, 0.9);
            color: white;
            border-radius: 9999px;
            padding: 12px 24px;
            font-family: 'Outfit', sans-serif;
            font-weight: bold;
            bottom: 30px;
        }

        /* Loading Overlay Fade */
        .fade-out { opacity: 0; pointer-events: none; transition: opacity 0.5s ease; }
    </style>
</head>
<body class="bg-[#050b09] text-white h-screen flex flex-col selection:bg-teal-500/30">

    <div class="fixed inset-0 -z-20 pointer-events-none">
        <div class="absolute top-[20%] left-[10%] w-[30vw] h-[30vw] rounded-full bg-emerald-900/20 blur-[120px] mix-blend-screen"></div>
        <div class="absolute bottom-[10%] right-[10%] w-[40vw] h-[40vw] rounded-full bg-teal-900/20 blur-[150px] mix-blend-screen"></div>
    </div>
    <div class="fixed inset-0 -z-10 pointer-events-none">
        <img src="{{ Vite::asset('resources/img/anatomy_hero_bg.png') }}" class="w-full h-full object-cover opacity-10 blur-md mix-blend-screen">
    </div>

    <!-- Navbar -->
    <nav class="w-full z-50 glass-nav h-[72px] flex-shrink-0">
        <div class="h-full px-6 flex items-center justify-between">
            <a href="/" class="flex items-center gap-3 group">
                <div class="w-9 h-9 relative flex items-center justify-center group-hover:scale-105 transition-transform duration-300">
                    <div class="absolute inset-0 border-[1.5px] border-teal-500/30 rounded-lg transform rotate-12 group-hover:rotate-90 transition-all duration-700"></div>
                    <div class="absolute inset-0 border-[1.5px] border-emerald-400/30 rounded-lg transform -rotate-12 group-hover:-rotate-90 transition-all duration-700"></div>
                    <div class="w-6 h-6 bg-gradient-to-br from-teal-400 to-emerald-500 rounded flex items-center justify-center relative z-10 shadow-[0_0_15px_rgba(45,212,191,0.5)]">
                        <svg class="w-3.5 h-3.5 text-[#050b09]" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                            <path d="M6 4h-1a2 2 0 0 0 -2 2v3.5a5.5 5.5 0 0 0 11 0v-3.5a2 2 0 0 0 -2 -2h-1" />
                            <path d="M8 15a6 6 0 1 0 12 0v-3" />
                            <path d="M11 3v2" />
                            <path d="M6 3v2" />
                            <path d="M18 10a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" />
                        </svg>
                    </div>
                </div>
                <span class="text-xl font-bold tracking-widest text-white">Medix<span class="text-teal-400">AR</span> <span class="text-gray-500 font-medium tracking-normal ml-2">| Explorer</span></span>
            </a>
            <div class="flex items-center gap-4">
                <a href="/dashboard" class="text-sm font-semibold text-gray-400 hover:text-white transition-colors">Exit Explorer</a>
            </div>
        </div>
    </nav>

    <!-- Main Workspace -->
    <main class="flex-grow flex overflow-hidden relative p-4 gap-4">

        <!-- Left Sidebar (Modules) -->
        <aside class="w-[300px] flex-shrink-0 h-full flex flex-col gap-4 relative z-10 hidden md:flex">
            <div class="glass-panel rounded-2xl p-6 h-full flex flex-col">
                <h3 class="text-xs text-teal-400 font-bold tracking-widest uppercase mb-6">Learning Modules</h3>
                
                <div class="flex flex-col gap-2 overflow-y-auto pr-2" id="module-list">
                    <!-- Buttons are generated by JS -->
                </div>
            </div>
        </aside>

        <!-- Center 3D Viewer Canvas -->
        <section class="flex-grow h-full relative rounded-2xl overflow-hidden border border-white/5 bg-black/40 shadow-inner">
            
            <div class="absolute top-6 left-6 z-10 flex gap-2">
                <button onclick="document.querySelector('model-viewer').cameraOrbit = '0deg 75deg 105%'" class="w-10 h-10 rounded-full bg-white/10 backdrop-blur-md flex items-center justify-center border border-white/20 hover:bg-white/20 transition tooltip-trigger" title="Reset View">
                    <svg class="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                    </svg>
                </button>
            </div>

            <div class="absolute top-6 right-6 z-10">
                <div class="px-3 py-1.5 rounded-full bg-gradient-to-r from-teal-500/20 to-emerald-500/20 border border-teal-500/30 text-xs font-bold text-teal-300 tracking-widest flex items-center gap-2 backdrop-blur-md">
                    <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
                    </svg>
                    AR READY
                </div>
            </div>

            <div class="absolute bottom-6 left-1/2 -translate-x-1/2 z-10 text-center pointer-events-none">
                <p class="text-xs text-gray-400 bg-black/50 px-4 py-2 rounded-full backdrop-blur-md border border-white/10" id="viewer-hint">
                    Loading model...
                </p>
            </div>

            <!-- THE 3D MODEL VIEWER -->
            <model-viewer 
                id="main-viewer"
                src="https://modelviewer.dev/shared-assets/models/Astronaut.glb" 
                alt="3D Anatomical Model"
                ar 
                ar-modes="webxr scene-viewer quick-look"
                camera-controls 
                auto-rotate
                rotation-per-second="30deg"
                shadow-intensity="1"
                environment-image="neutral"
                exposure="1.2"
                class="w-full h-full outline-none"
                style="--poster-color: transparent;">
            </model-viewer>

        </section>

        <!-- Right Sidebar (Details) -->
        <aside class="w-[350px] flex-shrink-0 h-full flex flex-col gap-4 relative z-10 hidden xl:flex">
            <div class="glass-panel rounded-2xl p-6 h-full flex flex-col overflow-y-auto">
                <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-xs font-semibold text-gray-300 w-fit mb-4" id="info-tag">
                    Nervous System
                </div>
                
                <h2 class="text-3xl font-bold mb-2" id="info-title">Brain Stem</h2>
                <p class="text-teal-400 text-sm font-medium mb-6" id="info-scientific">Truncus cerebri</p>

                <div class="space-y-6 text-sm text-gray-300 leading-relaxed border-t border-white/10 pt-6">
                    <p id="info-desc">
                        The brainstem is the posterior part of the brain, adjoining and structurally continuous with the spinal cord.
                    </p>

                    <div>
                        <h4 class="text-white font-semibold mb-2 flex items-center gap-2">
                            <svg class="w-4 h-4 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                            Key Functions
                        </h4>
                        <ul class="space-y-2 text-gray-400 pl-6 list-disc marker:text-teal-500" id="info-functions">
                            <li>Regulation of cardiac and respiratory function.</li>
                        </ul>
                    </div>

                    <div class="p-4 rounded-xl bg-teal-900/20 border border-teal-500/20">
                        <h4 class="text-teal-300 font-semibold mb-1 text-xs uppercase tracking-widest">Clinical Note</h4>
                        <p class="text-gray-400 text-xs" id="info-clinical">
                            Lesions in the brainstem can cause severe deficits.
                        </p>
                    </div>
                </div>

                <div class="mt-auto pt-6 border-t border-white/10">
                    <button class="w-full py-3 bg-white/10 hover:bg-white/20 border border-white/20 rounded-xl font-semibold transition-all flex items-center justify-center gap-2">
                        <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        Play Guided Tour
                    </button>
                </div>
            </div>
        </aside>

    </main>

    <script>
        // Anatomy Data
        const anatomyData = [
            {
                id: 'nervous',
                name: 'Nervous System',
                subtitle: 'Brain Stem & Cranial Nerves',
                title: 'Brain Stem',
                scientific: 'Truncus cerebri',
                desc: 'The brainstem is the posterior part of the brain, adjoining and structurally continuous with the spinal cord. In the human brain, the brainstem is composed of the midbrain, the pons, and the medulla oblongata.',
                functions: [
                    'Regulation of cardiac and respiratory function.',
                    'Maintains consciousness and regulates the sleep cycle.',
                    'Contains the nuclei of most cranial nerves.',
                    'Acts as the main motor and sensory innervation pathway to the face and neck.'
                ],
                clinical: 'Lesions in the brainstem can cause severe deficits including "locked-in syndrome" or disruption of vital autonomic functions resulting in coma or death.',
                modelSrc: "{{ asset('models/BrainStem.glb') }}"
            },
            {
                id: 'skeletal',
                name: 'Skeletal System',
                subtitle: 'Human Skull & Jaw',
                title: 'Human Skull',
                scientific: 'Cranium',
                desc: 'The skull is a bony structure that forms the head in vertebrates. It supports the structures of the face and provides a protective cavity for the brain.',
                functions: [
                    'Protects the brain from injury.',
                    'Fixes the distance between the eyes for stereoscopic vision.',
                    'Fixes the position of the ears to help localize sounds.',
                    'Supports the jaws and teeth for chewing.'
                ],
                clinical: 'Fractures of the skull can cause traumatic brain injury. The pterion is a particularly vulnerable area where the middle meningeal artery lies.',
                modelSrc: "{{ asset('models/BrainStem.glb') }}" // Placeholder: Using BrainStem until real skull.glb is downloaded
            },
            {
                id: 'cardio',
                name: 'Cardiovascular',
                subtitle: 'The Human Heart',
                title: 'Human Heart',
                scientific: 'Cor',
                desc: 'The heart is a muscular organ that pumps blood through the blood vessels of the circulatory system. The pumped blood carries oxygen and nutrients to the body, while carrying metabolic waste such as carbon dioxide to the lungs.',
                functions: [
                    'Pumps oxygenated blood to the body.',
                    'Pumps deoxygenated blood to the lungs.',
                    'Maintains blood pressure.',
                    'Works synchronously with the respiratory system.'
                ],
                clinical: 'Cardiovascular diseases are the most common cause of death globally. Coronary artery disease restricts blood flow to the heart muscle, leading to angina or myocardial infarction (heart attack).',
                modelSrc: "{{ asset('models/BrainStem.glb') }}" // Placeholder
            },
            {
                id: 'respiratory',
                name: 'Respiratory',
                subtitle: 'Lungs & Trachea',
                title: 'Human Lungs',
                scientific: 'Pulmones',
                desc: 'The lungs are the primary organs of the respiratory system in humans. Their function is to extract oxygen from the atmosphere and transfer it into the bloodstream, and to release carbon dioxide from the bloodstream into the atmosphere.',
                functions: [
                    'Facilitates gas exchange (oxygen in, carbon dioxide out).',
                    'Maintains pH balance in the blood.',
                    'Filters small blood clots.',
                    'Contains ACE which converts angiotensin I to angiotensin II.'
                ],
                clinical: 'Pneumonia is an inflammatory condition of the lung affecting primarily the small air sacs known as alveoli, usually caused by infection.',
                modelSrc: "{{ asset('models/BrainStem.glb') }}" // Placeholder
            }
        ];

        let currentModuleId = 'nervous';
        const modelViewer = document.getElementById('main-viewer');
        const loadingOverlay = document.getElementById('loading-overlay');
        const viewerHint = document.getElementById('viewer-hint');
        const moduleList = document.getElementById('module-list');

        // Render Sidebar Buttons
        function renderButtons() {
            moduleList.innerHTML = '';
            anatomyData.forEach(module => {
                const isActive = module.id === currentModuleId;
                const activeClasses = 'bg-teal-500/20 border-teal-500/30 text-white';
                const inactiveClasses = 'bg-white/5 border-transparent hover:bg-white/10 text-gray-300';
                
                const btn = document.createElement('button');
                btn.className = `w-full text-left p-4 rounded-xl border transition-all group ${isActive ? activeClasses : inactiveClasses}`;
                btn.onclick = () => selectModule(module.id);
                
                btn.innerHTML = `
                    <div class="flex items-center justify-between mb-1">
                        <span class="font-semibold ${isActive ? 'text-white' : 'group-hover:text-white'}">${module.name}</span>
                        ${isActive ? '<div class="w-2 h-2 rounded-full bg-teal-400 animate-pulse"></div>' : ''}
                    </div>
                    <p class="text-xs ${isActive ? 'text-gray-400' : 'text-gray-500'}">${module.subtitle}</p>
                `;
                moduleList.appendChild(btn);
            });
        }

        // Handle Module Selection
        function selectModule(id) {
            if (currentModuleId === id) return;
            currentModuleId = id;
            const data = anatomyData.find(m => m.id === id);
            
            // Show loading
            viewerHint.innerText = 'Loading model...';
            
            // Update UI elements
            document.getElementById('info-tag').innerText = data.name;
            document.getElementById('info-title').innerText = data.title;
            document.getElementById('info-scientific').innerText = data.scientific;
            document.getElementById('info-desc').innerText = data.desc;
            document.getElementById('info-clinical').innerText = data.clinical;
            
            const ul = document.getElementById('info-functions');
            ul.innerHTML = '';
            data.functions.forEach(f => {
                const li = document.createElement('li');
                li.innerText = f;
                ul.appendChild(li);
            });

            // Update model source
            modelViewer.src = data.modelSrc;
            
            renderButtons();
        }

        // Handle Model Loading Events
        modelViewer.addEventListener('load', () => {
            viewerHint.innerText = 'Scroll to zoom • Click & drag to rotate';
        });

        // Error Handling
        modelViewer.addEventListener('error', (event) => {
            console.error('Model Viewer Error:', event);
            viewerHint.innerText = 'Failed to load 3D model. Check console for details.';
        });

        // Initial Render
        renderButtons();
    </script>
</body>
</html>
